config {
  type: "view", 
}

CREATE VIEW `palziv-data-prod.presentation.dim_intercompany_sales_filter` AS (
WITH intercompany_filter AS (
  SELECT 'OFF' AS state, 0 AS intercompany_sales
  UNION ALL
  SELECT 'ON', 1
  UNION ALL
  SELECT 'ON', 2
  UNION ALL
  SELECT 'EXT', 0
  UNION ALL
  SELECT 'EXT', 1
  UNION ALL
  SELECT 'ALL', 0
  UNION ALL
  SELECT 'ALL', 1
  UNION ALL
  SELECT 'ALL', 2
)
SELECT state, intercompany_sales FROM intercompany_filter
)